### ISSUE TITLE
Not preview correctly in browser

### ISSUE THREAD

**Issue by thewinger** [eqot/atom-broadcast#7]
Using Markdown-preview (0.157.1) and broadcast (0.3.14)

![screen shot 2016-03-06 at 13 02 41](https://cloud.githubusercontent.com/assets/121455/13553983/d0f1d9c0-e39b-11e5-8147-b601a41733cd.png)

![image](https://cloud.githubusercontent.com/assets/121455/13553984/da54e52a-e39b-11e5-8de9-057afe02be67.png)

**Comment by eqot** [comment]
I guess that you have a focus on the left pane for the plain text, not on the right pane for the markdown preview. As [README.md](https://github.com/eqot/atom-broadcast) says, This package broadcasts content in a focused pane.
Can you try to click the right pane to focus it, and restart this package, please?

**Comment by thewinger** [comment]
Yes, my bad.
Sorry for the incovenience

**Comment by eqot** [comment]
No problem at all. It might be easy to misunderstand...
